// ===== 生物数据 =====
export class CreatureData {
    constructor() {
        // 生物数据库 - 80+ 生物，覆盖从太古宙到第四纪
        this.creatures = [
            // ===== 冥古宙 (46-40亿年前) =====
            {
                id: 'hadean_earth',
                name: '原始地球',
                period: '45-40亿年前',
                startYear: 4500,
                endYear: 4000,
                type: 'land',
                lat: 0,
                lon: 0,
                icon: '🔥',
                color: 0xff4500,
                size: '行星',
                diet: '无',
                habitat: '熔岩海洋',
                status: '已演化',
                description: '地球形成初期，表面被熔岩海洋覆盖。没有固体地壳，没有水，没有生命。月球刚刚形成，地球自转极快。'
            },
            {
                id: 'zircon',
                name: '锆石晶体',
                period: '44-40亿年前',
                startYear: 4400,
                endYear: 4000,
                type: 'land',
                lat: -30,
                lon: 115,
                icon: '💎',
                color: 0xffd700,
                size: '微米级',
                diet: '无',
                habitat: '地壳',
                status: '现存矿物',
                description: '地球上最古老的矿物，记录了早期地球环境信息。来自西澳大利亚的杰克山锆石是目前发现的最古老地球物质。'
            },
            
            // ===== 太古宙 (40-25亿年前) =====
            {
                id: 'cyanobacteria',
                name: '蓝藻',
                period: '35-25亿年前',
                startYear: 3500,
                endYear: 2500,
                type: 'marine',
                lat: 0,
                lon: 0,
                icon: '🦠',
                color: 0x4fc3f7,
                size: '微观',
                diet: '光合作用',
                habitat: '浅海',
                status: '现存后代',
                description: '地球上最早的光合生物之一，通过光合作用释放氧气，逐渐改变地球大气成分，为大氧化事件奠定基础。它们形成的叠层石是最早的生物沉积构造。'
            },
            {
                id: 'stromatolites',
                name: '叠层石',
                period: '35-5亿年前',
                startYear: 3500,
                endYear: 500,
                type: 'marine',
                lat: -20,
                lon: 120,
                icon: '🪨',
                color: 0x8d6e63,
                size: '厘米-米级',
                diet: '光合作用',
                habitat: '浅海',
                status: '现存（稀少）',
                description: '由蓝藻等微生物群落形成的层状沉积构造。它们是地球上最古老的生命记录，在澳大利亚、加拿大等地发现了35亿年前的叠层石。'
            },
            {
                id: 'archean_bacteria',
                name: '古细菌',
                period: '38-25亿年前',
                startYear: 3800,
                endYear: 2500,
                type: 'marine',
                lat: 10,
                lon: -20,
                icon: '🦠',
                color: 0x9c27b0,
                size: '微观',
                diet: '化学合成',
                habitat: '深海热泉',
                status: '现存后代',
                description: '极端环境微生物，生活在深海热泉等高温环境中。它们代表了生命演化树中最古老的分支之一。'
            },
            {
                id: 'prokaryotes',
                name: '原核生物群',
                period: '40-25亿年前',
                startYear: 4000,
                endYear: 2500,
                type: 'marine',
                lat: 5,
                lon: 45,
                icon: '🔬',
                color: 0x00bcd4,
                size: '微观',
                diet: '多样',
                habitat: '海洋',
                status: '现存',
                description: '细菌和古菌的统称，太古宙海洋中唯一的生命形式。它们开创了光合作用，改变了地球大气和海洋化学成分。'
            },
            {
                id: 'banded_iron',
                name: '条带状铁矿',
                period: '38-18亿年前',
                startYear: 3800,
                endYear: 1800,
                type: 'marine',
                lat: -15,
                lon: 118,
                icon: '⛓️',
                color: 0xb71c1c,
                size: '公里级',
                diet: '无',
                habitat: '海底',
                status: '化石记录',
                description: '蓝藻光合作用释放的氧气与海水中的二价铁反应形成三价铁沉积。条带状铁矿是地球大氧化事件的地质记录。'
            },
            
            // ===== 元古宙 (25-5.41亿年前) =====
            {
                id: 'acritarchs',
                name: '疑源类',
                period: '18-5.41亿年前',
                startYear: 1800,
                endYear: 541,
                type: 'marine',
                lat: 15,
                lon: 30,
                icon: '🔬',
                color: 0x9c27b0,
                size: '0.05-2毫米',
                diet: '光合作用/异养',
                habitat: '海洋',
                status: '灭绝',
                description: '元古宙海洋中最常见的浮游生物，可能是各种藻类的孢囊。它们的化石是元古宙地层定年的重要标志。形态多样，有球形、椭圆形等。'
            },
            {
                id: 'dickinsonia',
                name: '狄更逊水母',
                period: '5.58-5.41亿年前',
                startYear: 558,
                endYear: 541,
                type: 'marine',
                lat: -20,
                lon: 135,
                icon: '🫓',
                color: 0xff9800,
                size: '数毫米-1.4米',
                diet: '可能为吸收营养',
                habitat: '海底',
                status: '灭绝',
                description: '埃迪卡拉纪最具代表性的生物之一，呈扁平的椭圆形，表面有分节。它是已知最早的大型多细胞生物之一，但分类地位仍有争议。'
            },
            {
                id: 'spriggina',
                name: '斯普里格蠕虫',
                period: '5.55-5.41亿年前',
                startYear: 555,
                endYear: 541,
                type: 'marine',
                lat: -25,
                lon: 130,
                icon: '🐛',
                color: 0x8bc34a,
                size: '3-5厘米',
                diet: '未知',
                habitat: '海底',
                status: '灭绝',
                description: '埃迪卡拉纪的奇怪生物，身体呈两侧对称，前端有半月形头部。可能是节肢动物的祖先，但也有学者认为属于独立的灭绝门类。'
            },
            {
                id: 'kimberella',
                name: '金伯拉虫',
                period: '5.55-5.41亿年前',
                startYear: 555,
                endYear: 541,
                type: 'marine',
                lat: 60,
                lon: 75,
                icon: '🐌',
                color: 0xffb74d,
                size: '3-7厘米',
                diet: '刮食藻类',
                habitat: '海底',
                status: '灭绝',
                description: '可能是软体动物的祖先，外形像现代的帽贝。它留下了独特的爬行痕迹化石，是最早的动物活动证据之一。'
            },
            {
                id: 'charnia',
                name: '查恩盘虫',
                period: '5.70-5.41亿年前',
                startYear: 570,
                endYear: 541,
                type: 'marine',
                lat: 50,
                lon: -10,
                icon: '🌿',
                color: 0x66bb6a,
                size: '可达2米',
                diet: '未知',
                habitat: '深海',
                status: '灭绝',
                description: '最早的复杂多细胞生物之一，外形像羽毛或叶子。它没有口和消化系统，可能是通过身体表面吸收营养。'
            },
            {
                id: 'eukaryotes',
                name: '真核生物',
                period: '18-5亿年前',
                startYear: 1800,
                endYear: 500,
                type: 'marine',
                lat: 0,
                lon: 60,
                icon: '🔬',
                color: 0xe91e63,
                size: '微观-毫米',
                diet: '多样',
                habitat: '海洋',
                status: '现存',
                description: '具有细胞核的复杂细胞生物，包括原生生物、藻类、真菌、植物和动物的祖先。真核生物的出现是生命复杂化的关键一步。'
            },
            {
                id: 'red_algae',
                name: '红藻',
                period: '12-5亿年前',
                startYear: 1200,
                endYear: 500,
                type: 'marine',
                lat: 25,
                lon: -45,
                icon: '🌿',
                color: 0xc62828,
                size: '厘米级',
                diet: '光合作用',
                habitat: '浅海',
                status: '现存',
                description: '最早的多细胞藻类之一，在元古宙海洋中广泛分布。红藻的光合色素能够利用深海中有限的蓝光。'
            },
            
            // ===== 寒武纪 (5.41-4.85亿年前) =====
            {
                id: 'anomalocaris',
                name: '奇虾',
                period: '5.21-4.88亿年前',
                startYear: 521,
                endYear: 485,
                type: 'marine',
                lat: 20,
                lon: 110,
                icon: '🦐',
                color: 0xff5722,
                size: '0.6-2米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '寒武纪海洋的顶级掠食者，拥有巨大的复眼和强壮的前肢。化石最初被误认为不同的生物，后来才拼凑出完整的形象。它证明了早期生态系统已有复杂的食物链。'
            },
            {
                id: 'trilobite',
                name: '三叶虫',
                period: '5.21-2.52亿年前',
                startYear: 521,
                endYear: 252,
                type: 'marine',
                lat: 30,
                lon: -10,
                icon: '🐞',
                color: 0x795548,
                size: '1毫米-70厘米',
                diet: '杂食',
                habitat: '海底',
                status: '灭绝',
                description: '寒武纪最具代表性的生物，身体分为头、胸、尾三部分。它们是优秀的掘穴者和游泳者，存续了近3亿年，是化石记录中最丰富的节肢动物。'
            },
            {
                id: 'hallucigenia',
                name: '怪诞虫',
                period: '5.08-5.01亿年前',
                startYear: 508,
                endYear: 485,
                type: 'marine',
                lat: 40,
                lon: -120,
                icon: '🐛',
                color: 0x607d8b,
                size: '0.5-3厘米',
                diet: '可能为滤食',
                habitat: '海底',
                status: '灭绝',
                description: '怪诞虫因其奇特的外形而得名，最初化石被倒置解释。它有七对长腿，背上有棘刺。属于叶足动物，可能是现代节肢动物的近亲。'
            },
            {
                id: 'opabinia',
                name: '欧巴宾海蝎',
                period: '5.05-4.87亿年前',
                startYear: 505,
                endYear: 485,
                type: 'marine',
                lat: 50,
                lon: -95,
                icon: '🦑',
                color: 0x9c27b0,
                size: '4-7厘米',
                diet: '肉食',
                habitat: '海底',
                status: '灭绝',
                description: '有五只眼睛和一个像吸尘器一样的长鼻子，外形极其怪异。它是寒武纪大爆发中产生的奇特身体构型之一，没有现代近亲。'
            },
            {
                id: 'pikaia',
                name: '皮卡虫',
                period: '5.08-4.88亿年前',
                startYear: 508,
                endYear: 485,
                type: 'marine',
                lat: 45,
                lon: -125,
                icon: '🐟',
                color: 0x4caf50,
                size: '3-5厘米',
                diet: '滤食/食腐',
                habitat: '海底',
                status: '灭绝',
                description: '被认为是人类和所有脊椎动物的最早祖先。它具有原始的脊索，是脊索动物的最早代表。这条小鱼一样的生物改变了生命演化的方向。'
            },
            {
                id: 'wiwaxia',
                name: '威瓦亚虫',
                period: '5.20-5.05亿年前',
                startYear: 520,
                endYear: 505,
                type: 'marine',
                lat: 35,
                lon: 100,
                icon: '🐛',
                color: 0xffca28,
                size: '可达3厘米',
                diet: '刮食藻类',
                habitat: '海底',
                status: '灭绝',
                description: '身体覆盖着鳞片和尖刺的奇怪生物。它可能是软体动物和环节动物的共同祖先，展示了早期动物的实验性身体构型。'
            },
            {
                id: 'haikouichthys',
                name: '海口鱼',
                period: '5.18-5.13亿年前',
                startYear: 518,
                endYear: 513,
                type: 'marine',
                lat: 22,
                lon: 102,
                icon: '🐟',
                color: 0x81c784,
                size: '约2厘米',
                diet: '滤食',
                habitat: '浅海',
                status: '灭绝',
                description: '最早的脊椎动物之一，具有明显的头部和原始脊椎。来自云南澄江生物群，是脊椎动物起源的关键证据。'
            },
            {
                id: 'hallucigenia_2',
                name: '微网虫',
                period: '5.20-5.10亿年前',
                startYear: 520,
                endYear: 510,
                type: 'marine',
                lat: 38,
                lon: 115,
                icon: '🐛',
                color: 0x9e9e9e,
                size: '约2厘米',
                diet: '未知',
                habitat: '海底',
                status: '灭绝',
                description: '身体覆盖着六边形鳞片的叶足动物。它展示了早期动物外骨骼的多样性，可能是节肢动物演化中的重要一环。'
            },
            
            // ===== 奥陶纪 (4.85-4.44亿年前) =====
            {
                id: 'orthoceras',
                name: '直角石',
                period: '4.70-4.44亿年前',
                startYear: 470,
                endYear: 444,
                type: 'marine',
                lat: -10,
                lon: 15,
                icon: '🦑',
                color: 0x00bcd4,
                size: '可达9米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝（有后代）',
                description: '巨大的直壳鹦鹉螺类，奥陶纪海洋的顶级掠食者。它的壳呈圆锥形，内部有许多气室。现代鹦鹉螺是它的远亲。'
            },
            {
                id: 'astraspis',
                name: '星甲鱼',
                period: '4.50-4.20亿年前',
                startYear: 450,
                endYear: 420,
                type: 'marine',
                lat: 25,
                lon: -90,
                icon: '🐟',
                color: 0x8bc34a,
                size: '10-15厘米',
                diet: '滤食',
                habitat: '浅海',
                status: '灭绝',
                description: '最早的鱼类之一，属于无颌鱼类。身体覆盖着坚硬的骨板，没有成对的鳍。它们是早期脊椎动物演化的重要代表。'
            },
            {
                id: 'megalograptus',
                name: '巨型海蝎',
                period: '4.60-4.45亿年前',
                startYear: 460,
                endYear: 444,
                type: 'marine',
                lat: 35,
                lon: -70,
                icon: '🦞',
                color: 0x795548,
                size: '可达2.5米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '有史以来最大的节肢动物，巨大的海蝎子。它拥有强大的螯肢和尾刺，是奥陶纪海洋的霸主。体型巨大可能与当时高氧环境有关。'
            },
            {
                id: 'conodonts',
                name: '牙形石',
                period: '4.95-2.01亿年前',
                startYear: 495,
                endYear: 201,
                type: 'marine',
                lat: 0,
                lon: 0,
                icon: '🦷',
                color: 0xffeb3b,
                size: '数厘米',
                diet: '肉食/滤食',
                habitat: '海洋',
                status: '灭绝',
                description: '一类神秘的早期脊椎动物，只留下了牙齿化石。它们实际上是有鳗鱼状身体的鱼类，在奥陶纪海洋中广泛分布。'
            },
            {
                id: 'bryozoans',
                name: '苔藓动物',
                period: '4.80-0亿年前',
                startYear: 480,
                endYear: 0,
                type: 'marine',
                lat: 40,
                lon: 25,
                icon: '🪸',
                color: 0xffccbc,
                size: '毫米-厘米',
                diet: '滤食',
                habitat: '浅海',
                status: '现存',
                description: '微小的群居无脊椎动物，形成类似珊瑚的群落。奥陶纪时开始繁盛，是地层定年的重要标准化石。'
            },
            {
                id: 'graptolites',
                name: '笔石',
                period: '4.90-3.23亿年前',
                startYear: 490,
                endYear: 323,
                type: 'marine',
                lat: -20,
                lon: 45,
                icon: '🪶',
                color: 0x3e2723,
                size: '厘米级',
                diet: '滤食',
                habitat: '海洋',
                status: '灭绝',
                description: '群居的半索动物，漂浮在海洋中。它们的化石形似书写的笔触，因此得名。笔石是奥陶纪-志留纪重要的标准化石。'
            },
            
            // ===== 志留纪 (4.44-4.19亿年前) =====
            {
                id: 'cooksonia',
                name: '库克逊蕨',
                period: '4.33-3.93亿年前',
                startYear: 433,
                endYear: 393,
                type: 'plant',
                lat: -5,
                lon: 10,
                icon: '🌿',
                color: 0x4caf50,
                size: '数厘米',
                diet: '光合作用',
                habitat: '陆地',
                status: '灭绝',
                description: '最早登陆的植物之一，没有真正的根、茎、叶分化。呈简单的叉状，通过孢子繁殖。它开启了植物征服陆地的历史。'
            },
            {
                id: 'entelognathus',
                name: '全颌鱼',
                period: '4.25-4.19亿年前',
                startYear: 425,
                endYear: 419,
                type: 'marine',
                lat: 30,
                lon: 105,
                icon: '🐟',
                color: 0x2196f3,
                size: '约20厘米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '最早的具有完整上下颌的鱼类，被认为是现代有颌脊椎动物的祖先。颌的出现是脊椎动物演化史上最重要的创新之一。'
            },
            {
                id: 'rhyniella',
                name: '莱尼虫',
                period: '4.10-4.00亿年前',
                startYear: 410,
                endYear: 400,
                type: 'land',
                lat: 55,
                lon: -3,
                icon: '🪳',
                color: 0x5d4037,
                size: '毫米级',
                diet: '植食/腐食',
                habitat: '陆地',
                status: '灭绝',
                description: '最早登陆的六足动物之一，发现于苏格兰莱尼燧石层。它代表了节肢动物从海洋向陆地扩张的重要一步。'
            },
            {
                id: 'sea_scorpions',
                name: '板足鲎',
                period: '4.60-2.52亿年前',
                startYear: 460,
                endYear: 252,
                type: 'marine',
                lat: 20,
                lon: -85,
                icon: '🦂',
                color: 0x8d6e63,
                size: '10厘米-2.5米',
                diet: '肉食',
                habitat: '浅海/河口',
                status: '灭绝（有后代）',
                description: '志留纪-石炭纪的海洋霸主，外形介于蝎子和马蹄蟹之间。它们是最早的螯肢动物之一，现代的马蹄蟹是其后代。'
            },
            {
                id: 'euthycarcinoids',
                name: '宽铠虾',
                period: '4.40-2.90亿年前',
                startYear: 440,
                endYear: 290,
                type: 'marine',
                lat: 45,
                lon: 15,
                icon: '🦐',
                color: 0x795548,
                size: '数厘米-数十厘米',
                diet: '杂食',
                habitat: '海陆交界',
                status: '灭绝',
                description: '介于节肢动物和脊椎动物之间的神秘生物。它们可能是最早能够离开水体短暂活动的节肢动物之一。'
            },
            
            // ===== 泥盆纪 (4.19-3.59亿年前) =====
            {
                id: 'dunkleosteus',
                name: '邓氏鱼',
                period: '3.82-3.58亿年前',
                startYear: 382,
                endYear: 358,
                type: 'marine',
                lat: 10,
                lon: -80,
                icon: '🦈',
                color: 0x607d8b,
                size: '4-10米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '泥盆纪的海洋霸主，最大的盾皮鱼类。虽然没有真正的牙齿，但拥有锋利如剪刀的骨板。咬合力可达数吨，能咬碎任何猎物。'
            },
            {
                id: 'tiktaalik',
                name: '提塔利克鱼',
                period: '3.75亿年前',
                startYear: 375,
                endYear: 374,
                type: 'marine',
                lat: 15,
                lon: -75,
                icon: '🐟',
                color: 0x8d6e63,
                size: '1-2.5米',
                diet: '肉食',
                habitat: '浅海/河口',
                status: '灭绝',
                description: '鱼类向四足动物过渡的关键物种，具有腕状的鳍和可转动的颈部。它代表了脊椎动物从水生到陆生的重要一步。'
            },
            {
                id: 'archaeopteris',
                name: '古羊齿',
                period: '3.85-3.59亿年前',
                startYear: 385,
                endYear: 359,
                type: 'plant',
                lat: 5,
                lon: -5,
                icon: '🌲',
                color: 0x2e7d32,
                size: '可达30米',
                diet: '光合作用',
                habitat: '陆地',
                status: '灭绝',
                description: '最早的真正的树木，形成了地球上第一批森林。它的根系深广，对土壤和气候产生了深远影响，也改变了地球的碳循环。'
            },
            {
                id: 'ichthyostega',
                name: '鱼石螈',
                period: '3.65-3.60亿年前',
                startYear: 365,
                endYear: 360,
                type: 'land',
                lat: 60,
                lon: -45,
                icon: '🦎',
                color: 0x4caf50,
                size: '1-1.5米',
                diet: '肉食/杂食',
                habitat: '水陆交界',
                status: '灭绝',
                description: '最早的四足动物之一，具有明显的四肢和指头。虽然能在陆地上移动，但可能主要在水中生活。它是两栖动物的祖先。'
            },
            {
                id: 'bothriolepis',
                name: '沟鳞鱼',
                period: '4.00-3.58亿年前',
                startYear: 400,
                endYear: 358,
                type: 'marine',
                lat: -10,
                lon: 15,
                icon: '🐟',
                color: 0xa1887f,
                size: '约30厘米',
                diet: '植食/碎屑',
                habitat: '淡水/河口',
                status: '灭绝',
                description: '最常见的泥盆纪鱼类之一，属于盾皮鱼类。身体覆盖着厚重的骨板，是淡水生态系统的重要组成部分。'
            },
            {
                id: 'cladoselache',
                name: '裂口鲨',
                period: '3.80-3.60亿年前',
                startYear: 380,
                endYear: 360,
                type: 'marine',
                lat: 20,
                lon: -70,
                icon: '🦈',
                color: 0x607d8b,
                size: '约1米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝（有后代）',
                description: '最早的真正鲨鱼之一，具有流线型的身体和多个鳍。虽然保留了原始的骨板，但已经具备现代鲨鱼的基本形态。'
            },
            
            // ===== 石炭纪 (3.59-2.99亿年前) =====
            {
                id: 'meganeura',
                name: '巨脉蜻蜓',
                period: '3.05-2.99亿年前',
                startYear: 305,
                endYear: 299,
                type: 'flying',
                lat: 10,
                lon: 20,
                icon: '🦋',
                color: 0x9c27b0,
                size: '翼展75厘米',
                diet: '肉食',
                habitat: '森林',
                status: '灭绝',
                description: '史上最大的飞行昆虫，翼展可达75厘米。巨大的体型得益于石炭纪高氧环境。它捕食其他昆虫和小型脊椎动物。'
            },
            {
                id: 'arthropleura',
                name: '节胸蜈蚣',
                period: '3.45-2.80亿年前',
                startYear: 345,
                endYear: 280,
                type: 'land',
                lat: 25,
                lon: -10,
                icon: '🐛',
                color: 0x795548,
                size: '可达2.6米',
                diet: '植食',
                habitat: '森林',
                status: '灭绝',
                description: '史上最大的陆生无脊椎动物，一种巨型马陆。虽然体型骇人，但它是植食性的。高氧环境让它能够长到惊人的尺寸。'
            },
            {
                id: 'hylonomus',
                name: '林蜥',
                period: '3.12亿年前',
                startYear: 312,
                endYear: 311,
                type: 'land',
                lat: 45,
                lon: -60,
                icon: '🦎',
                color: 0x4caf50,
                size: '20-30厘米',
                diet: '昆虫',
                habitat: '森林',
                status: '灭绝',
                description: '最早的爬行动物之一，产羊膜卵，完全摆脱了对水体的依赖。这标志着脊椎动物真正征服了陆地。'
            },
            {
                id: 'lepidodendron',
                name: '鳞木',
                period: '3.59-2.72亿年前',
                startYear: 359,
                endYear: 272,
                type: 'plant',
                lat: 30,
                lon: -5,
                icon: '🌲',
                color: 0x33691e,
                size: '可达40米',
                diet: '光合作用',
                habitat: '沼泽森林',
                status: '灭绝',
                description: '石炭纪的巨型树木，形成广袤的沼泽森林。死后堆积的遗体经过地质作用变成了今天的煤炭。树干表面有鳞片状的纹路。'
            },
            {
                id: 'sigillaria',
                name: '封印木',
                period: '3.59-2.72亿年前',
                startYear: 359,
                endYear: 272,
                type: 'plant',
                lat: 35,
                lon: 0,
                icon: '🌴',
                color: 0x558b2f,
                size: '可达30米',
                diet: '光合作用',
                habitat: '沼泽森林',
                status: '灭绝',
                description: '石炭纪的另一种巨型树木，与鳞木一起形成了煤炭森林。树干上有独特的六边形叶痕。'
            },
            {
                id: 'eryops',
                name: '引螈',
                period: '3.10-2.80亿年前',
                startYear: 310,
                endYear: 280,
                type: 'land',
                lat: 38,
                lon: -95,
                icon: '🐸',
                color: 0x66bb6a,
                size: '1.5-2米',
                diet: '肉食',
                habitat: '沼泽/水域',
                status: '灭绝',
                description: '大型两栖动物，虽然能在陆地上活动，但仍依赖水体繁殖。它是石炭纪-二叠纪最常见的两栖动物之一。'
            },
            
            // ===== 二叠纪 (2.99-2.52亿年前) =====
            {
                id: 'dimetrodon',
                name: '异齿龙',
                period: '2.95-2.70亿年前',
                startYear: 295,
                endYear: 270,
                type: 'land',
                lat: 35,
                lon: -100,
                icon: '🦎',
                color: 0xff5722,
                size: '1-4米',
                diet: '肉食',
                habitat: '干旱平原',
                status: '灭绝',
                description: '著名的"背帆"爬行动物，常被误认为恐龙。它是盘龙类，比恐龙出现得更早。背帆可能用于体温调节。它是当时最大的掠食者之一。'
            },
            {
                id: 'scutosaurus',
                name: '盾甲龙',
                period: '2.60-2.52亿年前',
                startYear: 260,
                endYear: 252,
                type: 'land',
                lat: 55,
                lon: 60,
                icon: '🐢',
                color: 0x8bc34a,
                size: '可达3米',
                diet: '植食',
                habitat: '干旱地区',
                status: '灭绝',
                description: '一种大型的副爬行动物，身体覆盖着厚重的骨板。它是二叠纪的大型植食动物，能够防御大多数掠食者。'
            },
            {
                id: 'gorgonopsid',
                name: '丽齿兽',
                period: '2.70-2.52亿年前',
                startYear: 270,
                endYear: 252,
                type: 'land',
                lat: 45,
                lon: 25,
                icon: '🐺',
                color: 0xd32f2f,
                size: '2-4米',
                diet: '肉食',
                habitat: '多种环境',
                status: '灭绝',
                description: '二叠纪晚期最可怕的掠食者，属于合弓纲（似哺乳爬行动物）。它拥有类似剑齿虎的巨大犬齿，是当时陆地的霸主。'
            },
            {
                id: 'moschops',
                name: '麝足兽',
                period: '2.65-2.60亿年前',
                startYear: 265,
                endYear: 260,
                type: 'land',
                lat: -30,
                lon: 25,
                icon: '🐃',
                color: 0xa1887f,
                size: '2.7-5米',
                diet: '植食',
                habitat: '平原',
                status: '灭绝',
                description: '大型植食性似哺乳爬行动物，头骨厚重，可能用于撞头竞争。它代表了二叠纪陆生动物大型化的趋势。'
            },
            {
                id: 'lystrosaurus',
                name: '水龙兽',
                period: '2.55-2.50亿年前',
                startYear: 255,
                endYear: 250,
                type: 'land',
                lat: -60,
                lon: 25,
                icon: '🐗',
                color: 0x795548,
                size: '0.6-2.5米',
                diet: '植食',
                habitat: '多种环境',
                status: '灭绝',
                description: '二叠纪大灭绝后幸存下来的少数动物之一，成为三叠纪早期最丰富的陆生脊椎动物。它的广泛分布为大陆漂移学说提供了证据。'
            },
            
            // ===== 三叠纪 (2.52-2.01亿年前) =====
            {
                id: 'coelophysis',
                name: '腔骨龙',
                period: '2.15-1.96亿年前',
                startYear: 215,
                endYear: 196,
                type: 'land',
                lat: 35,
                lon: -105,
                icon: '🦖',
                color: 0x4caf50,
                size: '3-4米',
                diet: '肉食',
                habitat: '沙漠/河流',
                status: '灭绝',
                description: '最早的恐龙之一，轻盈的双足肉食恐龙。它体型小巧但行动敏捷，代表了三叠纪恐龙演化的早期阶段。'
            },
            {
                id: 'plateosaurus',
                name: '板龙',
                period: '2.14-2.04亿年前',
                startYear: 214,
                endYear: 204,
                type: 'land',
                lat: 45,
                lon: 10,
                icon: '🦕',
                color: 0x8bc34a,
                size: '可达10米',
                diet: '植食',
                habitat: '森林',
                status: '灭绝',
                description: '最早的大型恐龙之一，也是第一种被科学命名的恐龙。它是植食性的蜥脚类恐龙，能够双足站立取食高处的植物。'
            },
            {
                id: 'icthyosaur',
                name: '鱼龙',
                period: '2.50-9.0百万年前',
                startYear: 250,
                endYear: 90,
                type: 'marine',
                lat: 30,
                lon: 135,
                icon: '🐬',
                color: 0x2196f3,
                size: '1-15米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '鱼龙是爬行动物重返海洋的典范，外形酷似海豚。它们完全适应了海洋生活，是高效的游泳者和捕食者。'
            },
            {
                id: 'nothosaurus',
                name: '幻龙',
                period: '2.40-2.10亿年前',
                startYear: 240,
                endYear: 210,
                type: 'marine',
                lat: 25,
                lon: 15,
                icon: '🦎',
                color: 0x4caf50,
                size: '可达4米',
                diet: '肉食',
                habitat: '浅海/海岸',
                status: '灭绝（有后代）',
                description: '三叠纪的海生爬行动物，半水生生活。它们是蛇颈龙和沧龙的祖先，代表了爬行动物重返海洋的尝试。'
            },
            {
                id: 'pterosaur_early',
                name: '早期翼龙',
                period: '2.28-2.01亿年前',
                startYear: 228,
                endYear: 201,
                type: 'flying',
                lat: 40,
                lon: -5,
                icon: '🦅',
                color: 0x00bcd4,
                size: '翼展可达2米',
                diet: '昆虫/鱼类',
                habitat: '海岸/森林',
                status: '灭绝（有后代）',
                description: '最早能够飞行的脊椎动物，在三叠纪晚期出现。它们的翅膀由皮肤和肌肉构成，连接延长的第四指。'
            },
            {
                id: 'cynognathus',
                name: '犬颌兽',
                period: '2.47-2.37亿年前',
                startYear: 247,
                endYear: 237,
                type: 'land',
                lat: -35,
                lon: 25,
                icon: '🐕',
                color: 0x8d6e63,
                size: '可达1米',
                diet: '肉食',
                habitat: '多种环境',
                status: '灭绝',
                description: '三叠纪的似哺乳爬行动物，具有类似哺乳动物的特征。它的牙齿分化为门齿、犬齿和臼齿，是哺乳动物演化的重要一环。'
            },
            {
                id: 'mastodonsaurus',
                name: '乳齿螈',
                period: '2.47-2.01亿年前',
                startYear: 247,
                endYear: 201,
                type: 'land',
                lat: 50,
                lon: 10,
                icon: '🐸',
                color: 0x5d4037,
                size: '4-6米',
                diet: '肉食',
                habitat: '水域/沼泽',
                status: '灭绝',
                description: '三叠纪最大的两栖动物之一，头部巨大，眼睛位于头顶。它几乎完全生活在水中，以鱼类和其他小型动物为食。'
            },
            
            // ===== 侏罗纪 (2.01-1.45亿年前) =====
            {
                id: 'allosaurus',
                name: '异特龙',
                period: '1.55-1.45亿年前',
                startYear: 155,
                endYear: 145,
                type: 'land',
                lat: 38,
                lon: -110,
                icon: '🦖',
                color: 0xf44336,
                size: '8-12米',
                diet: '肉食',
                habitat: '平原/森林',
                status: '灭绝',
                description: '侏罗纪北美洲的顶级掠食者，比霸王龙早出现近1亿年。它拥有巨大的头骨和锋利的牙齿，能捕食大型蜥脚类恐龙。'
            },
            {
                id: 'brachiosaurus',
                name: '腕龙',
                period: '1.54-1.53亿年前',
                startYear: 154,
                endYear: 153,
                type: 'land',
                lat: 42,
                lon: -105,
                icon: '🦕',
                color: 0x8bc34a,
                size: '18-26米',
                diet: '植食',
                habitat: '森林',
                status: '灭绝',
                description: '侏罗纪最高大的恐龙之一，前肢比后肢长，能够取食高处的树冠。它的心脏需要极大的压力才能将血液输送到头部。'
            },
            {
                id: 'stegosaurus',
                name: '剑龙',
                period: '1.55-1.50亿年前',
                startYear: 155,
                endYear: 150,
                type: 'land',
                lat: 40,
                lon: -108,
                icon: '🦕',
                color: 0x4caf50,
                size: '9米',
                diet: '植食',
                habitat: '平原',
                status: '灭绝',
                description: '最著名的植食恐龙之一，背上有两排骨板和四根尖刺。它的脑很小，但骨盆有一个"第二大脑"的神经节。'
            },
            {
                id: 'archaeopteryx',
                name: '始祖鸟',
                period: '1.50-1.48亿年前',
                startYear: 150,
                endYear: 148,
                type: 'flying',
                lat: 48,
                lon: 11,
                icon: '🦅',
                color: 0xff9800,
                size: '约0.5米',
                diet: '昆虫/小型动物',
                habitat: '森林',
                status: '灭绝',
                description: '最著名的过渡化石，兼具恐龙和鸟类的特征。它有羽毛和翅膀，但也保留牙齿和尾骨。是恐龙演化为鸟类的关键证据。'
            },
            {
                id: 'diplodocus',
                name: '梁龙',
                period: '1.54-1.52亿年前',
                startYear: 154,
                endYear: 152,
                type: 'land',
                lat: 40,
                lon: -112,
                icon: '🦕',
                color: 0x9e9e9e,
                size: '25-35米',
                diet: '植食',
                habitat: '森林/平原',
                status: '灭绝',
                description: '超长的蜥脚类恐龙，尾巴像鞭子一样长。它的颈部可以水平摆动，取食低矮植被。是侏罗纪常见的长颈恐龙。'
            },
            {
                id: 'liopleurodon',
                name: '滑齿龙',
                period: '1.66-1.55亿年前',
                startYear: 166,
                endYear: 155,
                type: 'marine',
                lat: 52,
                lon: 0,
                icon: '🐊',
                color: 0x1565c0,
                size: '6-25米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '侏罗纪海洋的顶级掠食者，巨大的上龙类。它的头骨巨大，咬合力惊人，能捕食鱼龙和其他海洋爬行动物。'
            },
            {
                id: 'rhamphorhynchus',
                name: '喙嘴翼龙',
                period: '1.50-1.48亿年前',
                startYear: 150,
                endYear: 148,
                type: 'flying',
                lat: 45,
                lon: 8,
                icon: '🦇',
                color: 0x795548,
                size: '翼展1.8米',
                diet: '鱼类/昆虫',
                habitat: '海岸',
                status: '灭绝',
                description: '长尾巴的翼龙，尾部末端有菱形尾鳍。它们是敏捷的飞行者，可能在沿海水域捕食鱼类。'
            },
            {
                id: 'plesiosaurus',
                name: '蛇颈龙',
                period: '2.00-1.66亿年前',
                startYear: 200,
                endYear: 166,
                type: 'marine',
                lat: 50,
                lon: -2,
                icon: '🦕',
                color: 0x4caf50,
                size: '3-5米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '长颈的海洋爬行动物，具有四只桨状肢。它们优雅地在海洋中游动，捕食鱼类和头足类。是蛇颈龙类的典型代表。'
            },
            
            // ===== 白垩纪 (1.45-6600万年前) =====
            {
                id: 'trex',
                name: '霸王龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'land',
                lat: 45,
                lon: -105,
                icon: '🦖',
                color: 0x795548,
                size: '12-13米',
                diet: '肉食',
                habitat: '平原/森林',
                status: '灭绝',
                description: '最著名的恐龙，也是最大的陆地掠食者之一。它拥有所有陆地动物中最强的咬合力，咬合力可达数万牛顿。小短手是其标志性特征。'
            },
            {
                id: 'triceratops',
                name: '三角龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'land',
                lat: 48,
                lon: -102,
                icon: '🦕',
                color: 0x8bc34a,
                size: '8-9米',
                diet: '植食',
                habitat: '平原',
                status: '灭绝',
                description: '最著名的植食恐龙之一，有三只角和巨大的颈盾。它可能用角进行防御和种内竞争。是霸王龙的同时代邻居。'
            },
            {
                id: 'velociraptor',
                name: '伶盗龙',
                period: '7500-7100万年前',
                startYear: 75,
                endYear: 71,
                type: 'land',
                lat: 42,
                lon: 70,
                icon: '🦖',
                color: 0xff5722,
                size: '约2米',
                diet: '肉食',
                habitat: '沙漠',
                status: '灭绝',
                description: '聪明的掠食恐龙，身披羽毛，第二趾有镰刀状利爪。虽然体型比电影中小得多，但群体狩猎时非常危险。'
            },
            {
                id: 'pteranodon',
                name: '无齿翼龙',
                period: '8800-8050万年前',
                startYear: 88,
                endYear: 80.5,
                type: 'flying',
                lat: 38,
                lon: -95,
                icon: '🦅',
                color: 0x00bcd4,
                size: '翼展7米',
                diet: '鱼类',
                habitat: '海岸',
                status: '灭绝',
                description: '不是恐龙，而是会飞的爬行动物。巨大的头冠可能有多种功能，包括展示、体温调节和飞行稳定。'
            },
            {
                id: 'mosasaurus',
                name: '沧龙',
                period: '8200-6600万年前',
                startYear: 82,
                endYear: 66,
                type: 'marine',
                lat: 35,
                lon: -90,
                icon: '🐊',
                color: 0x3f51b5,
                size: '可达17米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '白垩纪海洋的顶级掠食者，巨大的海生蜥蜴。它拥有强壮的尾巴和四肢演化成的鳍，统治着白垩纪晚期的海洋。'
            },
            {
                id: 'spinosaurus',
                name: '棘龙',
                period: '9900-9350万年前',
                startYear: 99,
                endYear: 93.5,
                type: 'land',
                lat: 25,
                lon: 30,
                icon: '🦖',
                color: 0x5d4037,
                size: '14-15米',
                diet: '肉食/鱼类',
                habitat: '河流/海岸',
                status: '灭绝',
                description: '已知最长的肉食恐龙，背上有巨大的帆状结构。它适应半水生生活，以鱼类为主要食物，可能也会捕食其他恐龙。'
            },
            {
                id: 'ankylosaurus',
                name: '甲龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'land',
                lat: 50,
                lon: -105,
                icon: '🐢',
                color: 0x6d4c41,
                size: '6-8米',
                diet: '植食',
                habitat: '平原',
                status: '灭绝',
                description: '最完整的装甲恐龙之一，全身覆盖着骨质甲片和尖刺。尾锤是它的武器，可以重创掠食者。'
            },
            {
                id: 'quetzalcoatlus',
                name: '风神翼龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'flying',
                lat: 32,
                lon: -98,
                icon: '🦅',
                color: 0x795548,
                size: '翼展10-11米',
                diet: '肉食',
                habitat: '内陆',
                status: '灭绝',
                description: '史上最大的飞行动物之一，翼展可达11米。它能够滑翔长距离，是高效的捕食者，可能捕食小型恐龙和其他动物。'
            },
            {
                id: 'ammonite',
                name: '菊石',
                period: '4.10-0.66亿年前',
                startYear: 410,
                endYear: 66,
                type: 'marine',
                lat: 0,
                lon: 0,
                icon: '🐚',
                color: 0xffab91,
                size: '厘米-2米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '具有旋卷外壳的头足类动物，从泥盆纪一直延续到白垩纪末。它们是重要的标准化石，在白垩纪末大灭绝中消失。'
            },
            
            // ===== 古近纪 (6600-2300万年前) =====
            {
                id: 'gastornis',
                name: '加斯顿鸟',
                period: '5600-4500万年前',
                startYear: 56,
                endYear: 45,
                type: 'land',
                lat: 48,
                lon: 2,
                icon: '🐦',
                color: 0xff9800,
                size: '高约2米',
                diet: '肉食/植食',
                habitat: '森林',
                status: '灭绝',
                description: '巨大的不会飞的鸟类，有巨大的喙。它曾是古新世的顶级掠食者之一，填补了恐龙灭绝后的生态位。'
            },
            {
                id: 'uintatherium',
                name: '尤因它兽',
                period: '5600-3400万年前',
                startYear: 56,
                endYear: 34,
                type: 'land',
                lat: 40,
                lon: -110,
                icon: '🦏',
                color: 0x8d6e63,
                size: '可达4米',
                diet: '植食',
                habitat: '森林/沼泽',
                status: '灭绝',
                description: '早期的巨型植食哺乳动物，头部有多个骨质突起和尖牙。它代表了哺乳动物体型增大的早期尝试。'
            },
            {
                id: 'basilosaurus',
                name: '龙王鲸',
                period: '4100-3400万年前',
                startYear: 41,
                endYear: 34,
                type: 'marine',
                lat: 25,
                lon: 30,
                icon: '🐋',
                color: 0x607d8b,
                size: '可达18米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '早期的鲸鱼，具有细长的身体和微小的后肢。它是鲸类从陆地返回海洋演化过程中的过渡类型。'
            },
            {
                id: 'paraceratherium',
                name: '巨犀',
                period: '3400-2300万年前',
                startYear: 34,
                endYear: 23,
                type: 'land',
                lat: 35,
                lon: 65,
                icon: '🦏',
                color: 0x795548,
                size: '肩高4.8米',
                diet: '植食',
                habitat: '草原/森林',
                status: '灭绝',
                description: '史上最大的陆地哺乳动物，体型可与蜥脚类恐龙相比。它没有角，依靠巨大的体型来防御掠食者。'
            },
            {
                id: 'pakicetus',
                name: '巴基鲸',
                period: '5000-4800万年前',
                startYear: 50,
                endYear: 48,
                type: 'land',
                lat: 30,
                lon: 70,
                icon: '🐕',
                color: 0x5d4037,
                size: '约1-2米',
                diet: '肉食/鱼类',
                habitat: '河流/海岸',
                status: '灭绝',
                description: '最早的鲸类祖先之一，外形像狼，但已经开始适应水生生活。它的耳朵结构显示它能够在水中听到声音。'
            },
            {
                id: 'andrewsarchus',
                name: '安氏中兽',
                period: '4800-4100万年前',
                startYear: 48,
                endYear: 41,
                type: 'land',
                lat: 45,
                lon: 110,
                icon: '🐺',
                color: 0x4e342e,
                size: '可达5米',
                diet: '肉食',
                habitat: '草原',
                status: '灭绝',
                description: '史上最大的陆生食肉哺乳动物，头骨巨大，咬合力惊人。它代表了古近纪哺乳动物掠食者的巅峰。'
            },
            
            // ===== 新近纪 (2300万年-260万年前) =====
            {
                id: 'megalodon',
                name: '巨齿鲨',
                period: '2300-360万年前',
                startYear: 23,
                endYear: 3.6,
                type: 'marine',
                lat: 20,
                lon: -75,
                icon: '🦈',
                color: 0x607d8b,
                size: '可达18米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '史上最大的掠食性鱼类，牙齿可达18厘米。它能捕食鲸鱼和其他大型海洋动物，是有史以来最强大的掠食者之一。'
            },
            {
                id: 'smilodon',
                name: '剑齿虎',
                period: '250万年前-1万年前',
                startYear: 2.5,
                endYear: 0.01,
                type: 'land',
                lat: -25,
                lon: -60,
                icon: '🐅',
                color: 0xff9800,
                size: '可达400公斤',
                diet: '肉食',
                habitat: '草原/森林',
                status: '灭绝',
                description: '著名的剑齿猫科动物，拥有超长的上犬齿。它用强壮的前肢制服猎物，然后用利齿给予致命一击。'
            },
            {
                id: 'woolly_mammoth',
                name: '猛犸象',
                period: '40万年前-4000年前',
                startYear: 0.4,
                endYear: 0.004,
                type: 'land',
                lat: 65,
                lon: 75,
                icon: '🐘',
                color: 0x9e9e9e,
                size: '肩高3.4米',
                diet: '植食',
                habitat: '苔原/草原',
                status: '灭绝',
                description: '冰河时代的标志性动物，身披厚毛，长有弯曲的长牙。它们适应了寒冷的北极环境，与人类共存了很长时间。'
            },
            {
                id: 'australopithecus',
                name: '南方古猿',
                period: '400-200万年前',
                startYear: 4,
                endYear: 2,
                type: 'land',
                lat: -25,
                lon: 25,
                icon: '🦍',
                color: 0x8d6e63,
                size: '身高1-1.4米',
                diet: '杂食',
                habitat: '稀树草原',
                status: '灭绝（有人类后代）',
                description: '最早的人科动物之一，著名的"露西"就属于这个属。它们已经能够直立行走，但脑容量还很小。是人类演化路上的重要一步。'
            },
            {
                id: 'homohabilis',
                name: '能人',
                period: '240-140万年前',
                startYear: 2.4,
                endYear: 1.4,
                type: 'land',
                lat: -3,
                lon: 35,
                icon: '🧑',
                color: 0xd7ccc8,
                size: '身高1-1.3米',
                diet: '杂食',
                habitat: '稀树草原',
                status: '灭绝（有人类后代）',
                description: '最早的人属成员，能够制造石器工具。"能人"意为"能干的人"，标志着人类技术能力的开端。'
            },
            {
                id: 'paranthropus',
                name: '傍人',
                period: '270-120万年前',
                startYear: 2.7,
                endYear: 1.2,
                type: 'land',
                lat: -25,
                lon: 28,
                icon: '🦍',
                color: 0x5d4037,
                size: '身高1.3-1.4米',
                diet: '植食',
                habitat: '稀树草原',
                status: '灭绝',
                description: '人科中的一个旁支，拥有巨大的颌骨和咀嚼肌，适应坚硬的植物性食物。它们与人类祖先分道扬镳，最终灭绝。'
            },
            {
                id: 'deinotherium',
                name: '恐象',
                period: '2300-780万年前',
                startYear: 23,
                endYear: 7.8,
                type: 'land',
                lat: 10,
                lon: 40,
                icon: '🐘',
                color: 0x795548,
                size: '肩高3.5-4米',
                diet: '植食',
                habitat: '森林/草原',
                status: '灭绝',
                description: '长鼻目动物，下颌有两根向下弯曲的象牙。它的长鼻可能用于卷取树叶和草。是中新世-上新世的重要植食动物。'
            },
            
            // ===== 第四纪 (260万年前-现在) =====
            {
                id: 'neanderthal',
                name: '尼安德特人',
                period: '40-4万年前',
                startYear: 0.4,
                endYear: 0.04,
                type: 'land',
                lat: 50,
                lon: 10,
                icon: '🧑',
                color: 0xd7ccc8,
                size: '身高1.6-1.7米',
                diet: '肉食为主',
                habitat: '欧洲/西亚',
                status: '灭绝（部分基因融入人类）',
                description: '现代人的近亲，适应寒冷气候。他们有埋葬死者的习俗，可能使用语言和符号。现代人类有1-4%的尼安德特人基因。'
            },
            {
                id: 'saber_toothed_cat',
                name: '致命刃齿虎',
                period: '250万年前-1万年前',
                startYear: 2.5,
                endYear: 0.01,
                type: 'land',
                lat: 35,
                lon: -120,
                icon: '🐅',
                color: 0xff5722,
                size: '可达400公斤',
                diet: '肉食',
                habitat: '多种环境',
                status: '灭绝',
                description: '北美洲的剑齿猫科动物，拥有超长的上犬齿。它专门捕食大型植食动物，在更新世末大灭绝中消失。'
            },
            {
                id: 'ground_sloth',
                name: '大地懒',
                period: '350万年前-1万年前',
                startYear: 3.5,
                endYear: 0.01,
                type: 'land',
                lat: -15,
                lon: -60,
                icon: '🦥',
                color: 0x8d6e63,
                size: '可达6米',
                diet: '植食',
                habitat: '森林/草原',
                status: '灭绝',
                description: '巨大的地懒，体型可与大象相比。它能够用后足站立取食高处的树叶，是最大的陆生树懒。'
            },
            {
                id: 'woolly_rhino',
                name: '披毛犀',
                period: '35万年前-1万年前',
                startYear: 0.35,
                endYear: 0.01,
                type: 'land',
                lat: 55,
                lon: 60,
                icon: '🦏',
                color: 0x795548,
                size: '可达2吨',
                diet: '植食',
                habitat: '苔原/草原',
                status: '灭绝',
                description: '适应寒冷气候的犀牛，身披厚毛。著名的"猛犸犀"洞穴壁画描绘的就是它们。与猛犸象一样在末次冰期结束时灭绝。'
            },
            {
                id: 'cave_lion',
                name: '洞狮',
                period: '30万年前-1.3万年前',
                startYear: 0.3,
                endYear: 0.013,
                type: 'land',
                lat: 48,
                lon: 12,
                icon: '🦁',
                color: 0xffd54f,
                size: '可达300公斤',
                diet: '肉食',
                habitat: '苔原/草原',
                status: '灭绝',
                description: '比现代狮子更大的冰河时代掠食者，适应寒冷环境。它们可能是史前人类洞穴壁画的主题。'
            },
            {
                id: 'irish_elk',
                name: '大角鹿',
                period: '40万年前-7700年前',
                startYear: 0.4,
                endYear: 0.0077,
                type: 'land',
                lat: 53,
                lon: -8,
                icon: '🦌',
                color: 0x8d6e63,
                size: '肩高2.1米',
                diet: '植食',
                habitat: '苔原/草原',
                status: '灭绝',
                description: '拥有巨大鹿角的鹿，角展可达3.6米。虽然名为"爱尔兰"，但分布遍及欧亚大陆。是人类猎捕和环境变化的受害者。'
            },
            {
                id: 'dire_wolf',
                name: '恐狼',
                period: '12.5万年前-9500年前',
                startYear: 0.125,
                endYear: 0.0095,
                type: 'land',
                lat: 35,
                lon: -110,
                icon: '🐺',
                color: 0x616161,
                size: '可达68公斤',
                diet: '肉食',
                habitat: '多种环境',
                status: '灭绝',
                description: '比现代灰狼更大更重的掠食者，强大的咬合力适合碎骨。著名的拉布雷亚沥青坑保存了大量恐狼化石。'
            },
            {
                id: 'homo_erectus',
                name: '直立人',
                period: '190-14万年前',
                startYear: 1.9,
                endYear: 0.14,
                type: 'land',
                lat: -7,
                lon: 110,
                icon: '🧑',
                color: 0xbcaaa4,
                size: '身高1.5-1.8米',
                diet: '肉食/杂食',
                habitat: '多种环境',
                status: '灭绝（有人类后代）',
                description: '第一个完全直立行走的人属成员，第一个走出非洲的人类祖先。他们使用阿舍利手斧，可能已会用火。北京猿人就属于直立人。'
            },
            {
                id: 'cave_bear',
                name: '洞熊',
                period: '25-2.4万年前',
                startYear: 0.25,
                endYear: 0.024,
                type: 'land',
                lat: 46,
                lon: 10,
                icon: '🐻',
                color: 0x5d4037,
                size: '可达1吨',
                diet: '杂食',
                habitat: '洞穴/森林',
                status: '灭绝',
                description: '比现代棕熊更大的熊类，在冰河时代的欧洲广泛分布。它们与尼安德特人和早期现代人共享洞穴。'
            }
        ];
        
        // 生物分类数据
        this.taxonomy = {
            '蓝藻': { domain: '细菌域', phylum: '蓝藻门', class: '-', order: '色球藻目' },
            '三叶虫': { domain: '真核域', phylum: '节肢动物门', class: '三叶虫纲', order: '多种目' },
            '奇虾': { domain: '真核域', phylum: '节肢动物门', class: '恐虾纲', order: '放射齿目' },
            '皮卡虫': { domain: '真核域', phylum: '脊索动物门', class: '头索纲', order: '-' },
            '海口鱼': { domain: '真核域', phylum: '脊椎动物门', class: '无颌纲', order: '昆明鱼目' },
            '邓氏鱼': { domain: '真核域', phylum: '脊椎动物门', class: '盾皮鱼纲', order: '节颈鱼目' },
            '腔骨龙': { domain: '真核域', phylum: '脊索动物门', class: '蜥形纲', order: '兽脚亚目' },
            '霸王龙': { domain: '真核域', phylum: '脊索动物门', class: '蜥形纲', order: '兽脚亚目' },
            '三角龙': { domain: '真核域', phylum: '脊索动物门', class: '蜥形纲', order: '角龙下目' },
            '始祖鸟': { domain: '真核域', phylum: '脊索动物门', class: '蜥形纲', order: '始祖鸟目' },
            '鱼龙': { domain: '真核域', phylum: '脊索动物门', class: '双孔亚纲', order: '鱼龙目' },
            '沧龙': { domain: '真核域', phylum: '脊索动物门', class: '双孔亚纲', order: '有鳞目' },
            '龙王鲸': { domain: '真核域', phylum: '脊索动物门', class: '哺乳纲', order: '鲸偶蹄目' },
            '猛犸象': { domain: '真核域', phylum: '脊索动物门', class: '哺乳纲', order: '长鼻目' },
            '剑齿虎': { domain: '真核域', phylum: '脊索动物门', class: '哺乳纲', order: '食肉目' },
            '南方古猿': { domain: '真核域', phylum: '脊索动物门', class: '哺乳纲', order: '灵长目' },
            '尼安德特人': { domain: '真核域', phylum: '脊索动物门', class: '哺乳纲', order: '灵长目' }
        };
    }
    
    // 获取指定年代存在的生物
    getCreaturesAtYear(year) {
        return this.creatures.filter(creature => {
            return year <= creature.startYear && year >= creature.endYear;
        });
    }
    
    // 根据ID获取生物
    getCreatureById(id) {
        return this.creatures.find(c => c.id === id);
    }
    
    // 按类型筛选生物
    getCreaturesByType(type) {
        return this.creatures.filter(c => c.type === type);
    }
    
    // 搜索生物
    searchCreatures(query) {
        const lowerQuery = query.toLowerCase();
        return this.creatures.filter(c => 
            c.name.toLowerCase().includes(lowerQuery) ||
            c.description.toLowerCase().includes(lowerQuery)
        );
    }
    
    // 获取所有生物
    getAllCreatures() {
        return this.creatures;
    }
    
    // 获取生物总数
    getCreatureCount() {
        return this.creatures.length;
    }
    
    // 获取生物类型统计
    getTypeStats() {
        const stats = {};
        this.creatures.forEach(c => {
            stats[c.type] = (stats[c.type] || 0) + 1;
        });
        return stats;
    }
    
    // 获取年代统计
    getEraStats() {
        const eras = [
            { name: '冥古宙', start: 4600, end: 4000 },
            { name: '太古宙', start: 4000, end: 2500 },
            { name: '元古宙', start: 2500, end: 541 },
            { name: '古生代', start: 541, end: 252 },
            { name: '中生代', start: 252, end: 66 },
            { name: '新生代', start: 66, end: 0 }
        ];
        
        return eras.map(era => ({
            ...era,
            count: this.creatures.filter(c => 
                c.startYear >= era.end && c.endYear <= era.start
            ).length
        }));
    }
    
    // 获取生物分类信息
    getTaxonomy(creatureName) {
        return this.taxonomy[creatureName] || null;
    }
    
    // 获取相关生物（同类型或同年代）
    getRelatedCreatures(creature, limit = 3) {
        return this.creatures
            .filter(c => c.id !== creature.id && c.type === creature.type)
            .slice(0, limit);
    }
    
    // 搜索生物
    searchCreatures(query, filterType = 'all') {
        if (!query && filterType === 'all') {
            return [];
        }
        
        return this.creatures.filter(c => {
            // 类型筛选
            if (filterType !== 'all') {
                if (filterType === 'dinosaur' && c.type !== 'dinosaur') return false;
                if (filterType === 'marine' && c.type !== 'marine') return false;
                if (filterType === 'land' && c.type !== 'land' && c.type !== 'mammal' && c.type !== 'reptile') return false;
                if (filterType === 'mammal' && c.type !== 'mammal') return false;
            }
            
            // 文本搜索
            if (!query) return true;
            
            const searchFields = [
                c.name,
                c.description,
                c.period,
                c.habitat,
                c.diet,
                c.type
            ];
            
            return searchFields.some(field => 
                field && field.toLowerCase().includes(query)
            );
        });
    }
    
    // 根据ID获取生物
    getCreatureById(id) {
        return this.creatures.find(c => c.id === id);
    }
}
