// ===== 生物数据 =====
export class CreatureData {
    constructor() {
        // 生物数据库
        this.creatures = [
            // ===== 太古宙 (40-25亿年前) =====
            {
                id: 'cyanobacteria',
                name: '蓝藻',
                period: '35-25亿年前',
                startYear: 3500,
                endYear: 2500,
                type: 'marine',
                lat: 0,
                lon: 0,
                icon: '🦠',
                color: 0x4fc3f7,
                size: '微观',
                diet: '光合作用',
                habitat: '浅海',
                status: '现存后代',
                description: '地球上最早的光合生物之一，通过光合作用释放氧气，逐渐改变地球大气成分，为大氧化事件奠定基础。它们形成的叠层石是最早的生物沉积构造。'
            },
            
            // ===== 元古宙 (25-5.41亿年前) =====
            {
                id: 'acritarchs',
                name: '疑源类',
                period: '18-5.41亿年前',
                startYear: 1800,
                endYear: 541,
                type: 'marine',
                lat: 15,
                lon: 30,
                icon: '🔬',
                color: 0x9c27b0,
                size: '0.05-2毫米',
                diet: '光合作用/异养',
                habitat: '海洋',
                status: '灭绝',
                description: '元古宙海洋中最常见的浮游生物，可能是各种藻类的孢囊。它们的化石是元古宙地层定年的重要标志。形态多样，有球形、椭圆形等。'
            },
            {
                id: 'dickinsonia',
                name: '狄更逊水母',
                period: '5.58-5.41亿年前',
                startYear: 558,
                endYear: 541,
                type: 'marine',
                lat: -20,
                lon: 135,
                icon: '🫓',
                color: 0xff9800,
                size: '数毫米-1.4米',
                diet: '可能为吸收营养',
                habitat: '海底',
                status: '灭绝',
                description: '埃迪卡拉纪最具代表性的生物之一，呈扁平的椭圆形，表面有分节。它是已知最早的大型多细胞生物之一，但分类地位仍有争议。'
            },
            {
                id: 'spriggina',
                name: '斯普里格蠕虫',
                period: '5.55-5.41亿年前',
                startYear: 555,
                endYear: 541,
                type: 'marine',
                lat: -25,
                lon: 130,
                icon: '🐛',
                color: 0x8bc34a,
                size: '3-5厘米',
                diet: '未知',
                habitat: '海底',
                status: '灭绝',
                description: '埃迪卡拉纪的奇怪生物，身体呈两侧对称，前端有半月形头部。可能是节肢动物的祖先，但也有学者认为属于独立的灭绝门类。'
            },
            
            // ===== 寒武纪 (5.41-4.85亿年前) =====
            {
                id: 'anomalocaris',
                name: '奇虾',
                period: '5.21-4.88亿年前',
                startYear: 521,
                endYear: 485,
                type: 'marine',
                lat: 20,
                lon: 110,
                icon: '🦐',
                color: 0xff5722,
                size: '0.6-2米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '寒武纪海洋的顶级掠食者，拥有巨大的复眼和强壮的前肢。化石最初被误认为不同的生物，后来才拼凑出完整的形象。它证明了早期生态系统已有复杂的食物链。'
            },
            {
                id: 'trilobite',
                name: '三叶虫',
                period: '5.21-2.52亿年前',
                startYear: 521,
                endYear: 252,
                type: 'marine',
                lat: 30,
                lon: -10,
                icon: '🐞',
                color: 0x795548,
                size: '1毫米-70厘米',
                diet: '杂食',
                habitat: '海底',
                status: '灭绝',
                description: '寒武纪最具代表性的生物，身体分为头、胸、尾三部分。它们是优秀的掘穴者和游泳者，存续了近3亿年，是化石记录中最丰富的节肢动物。'
            },
            {
                id: 'hallucigenia',
                name: '怪诞虫',
                period: '5.08-5.01亿年前',
                startYear: 508,
                endYear: 485,
                type: 'marine',
                lat: 40,
                lon: -120,
                icon: '🐛',
                color: 0x607d8b,
                size: '0.5-3厘米',
                diet: '可能为滤食',
                habitat: '海底',
                status: '灭绝',
                description: '怪诞虫因其奇特的外形而得名，最初化石被倒置解释。它有七对长腿，背上有棘刺。属于叶足动物，可能是现代节肢动物的近亲。'
            },
            {
                id: 'opabinia',
                name: '欧巴宾海蝎',
                period: '5.05-4.87亿年前',
                startYear: 505,
                endYear: 485,
                type: 'marine',
                lat: 50,
                lon: -95,
                icon: '🦑',
                color: 0x9c27b0,
                size: '4-7厘米',
                diet: '肉食',
                habitat: '海底',
                status: '灭绝',
                description: '有五只眼睛和一个像吸尘器一样的长鼻子，外形极其怪异。它是寒武纪大爆发中产生的奇特身体构型之一，没有现代近亲。'
            },
            {
                id: 'pikaia',
                name: '皮卡虫',
                period: '5.08-4.88亿年前',
                startYear: 508,
                endYear: 485,
                type: 'marine',
                lat: 45,
                lon: -125,
                icon: '🐟',
                color: 0x4caf50,
                size: '3-5厘米',
                diet: '滤食/食腐',
                habitat: '海底',
                status: '灭绝',
                description: '被认为是人类和所有脊椎动物的最早祖先。它具有原始的脊索，是脊索动物的最早代表。这条小鱼一样的生物改变了生命演化的方向。'
            },
            
            // ===== 奥陶纪 (4.85-4.44亿年前) =====
            {
                id: 'orthoceras',
                name: '直角石',
                period: '4.70-4.44亿年前',
                startYear: 470,
                endYear: 444,
                type: 'marine',
                lat: -10,
                lon: 15,
                icon: '🦑',
                color: 0x00bcd4,
                size: '可达9米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝（有后代）',
                description: '巨大的直壳鹦鹉螺类，奥陶纪海洋的顶级掠食者。它的壳呈圆锥形，内部有许多气室。现代鹦鹉螺是它的远亲。'
            },
            {
                id: 'astraspis',
                name: '星甲鱼',
                period: '4.50-4.20亿年前',
                startYear: 450,
                endYear: 420,
                type: 'marine',
                lat: 25,
                lon: -90,
                icon: '🐟',
                color: 0x8bc34a,
                size: '10-15厘米',
                diet: '滤食',
                habitat: '浅海',
                status: '灭绝',
                description: '最早的鱼类之一，属于无颌鱼类。身体覆盖着坚硬的骨板，没有成对的鳍。它们是早期脊椎动物演化的重要代表。'
            },
            {
                id: 'megalograptus',
                name: '巨型海蝎',
                period: '4.60-4.45亿年前',
                startYear: 460,
                endYear: 444,
                type: 'marine',
                lat: 35,
                lon: -70,
                icon: '🦞',
                color: 0x795548,
                size: '可达2.5米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '有史以来最大的节肢动物，巨大的海蝎子。它拥有强大的螯肢和尾刺，是奥陶纪海洋的霸主。体型巨大可能与当时高氧环境有关。'
            },
            
            // ===== 志留纪 (4.44-4.19亿年前) =====
            {
                id: 'cooksonia',
                name: '库克逊蕨',
                period: '4.33-3.93亿年前',
                startYear: 433,
                endYear: 393,
                type: 'plant',
                lat: -5,
                lon: 10,
                icon: '🌿',
                color: 0x4caf50,
                size: '数厘米',
                diet: '光合作用',
                habitat: '陆地',
                status: '灭绝',
                description: '最早登陆的植物之一，没有真正的根、茎、叶分化。呈简单的叉状，通过孢子繁殖。它开启了植物征服陆地的历史。'
            },
            {
                id: 'entelognathus',
                name: '全颌鱼',
                period: '4.25-4.19亿年前',
                startYear: 425,
                endYear: 419,
                type: 'marine',
                lat: 30,
                lon: 105,
                icon: '🐟',
                color: 0x2196f3,
                size: '约20厘米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '最早的具有完整上下颌的鱼类，被认为是现代有颌脊椎动物的祖先。颌的出现是脊椎动物演化史上最重要的创新之一。'
            },
            
            // ===== 泥盆纪 (4.19-3.59亿年前) =====
            {
                id: 'dunkleosteus',
                name: '邓氏鱼',
                period: '3.82-3.58亿年前',
                startYear: 382,
                endYear: 358,
                type: 'marine',
                lat: 10,
                lon: -80,
                icon: '🦈',
                color: 0x607d8b,
                size: '4-10米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '泥盆纪的海洋霸主，最大的盾皮鱼类。虽然没有真正的牙齿，但拥有锋利如剪刀的骨板。咬合力可达数吨，能咬碎任何猎物。'
            },
            {
                id: 'tiktaalik',
                name: '提塔利克鱼',
                period: '3.75亿年前',
                startYear: 375,
                endYear: 374,
                type: 'marine',
                lat: 15,
                lon: -75,
                icon: '🐟',
                color: 0x8d6e63,
                size: '1-2.5米',
                diet: '肉食',
                habitat: '浅海/河口',
                status: '灭绝',
                description: '鱼类向四足动物过渡的关键物种，具有腕状的鳍和可转动的颈部。它代表了脊椎动物从水生到陆生的重要一步。'
            },
            {
                id: 'archaeopteris',
                name: '古羊齿',
                period: '3.85-3.59亿年前',
                startYear: 385,
                endYear: 359,
                type: 'plant',
                lat: 5,
                lon: -5,
                icon: '🌲',
                color: 0x2e7d32,
                size: '可达30米',
                diet: '光合作用',
                habitat: '陆地',
                status: '灭绝',
                description: '最早的真正的树木，形成了地球上第一批森林。它的根系深广，对土壤和气候产生了深远影响，也改变了地球的碳循环。'
            },
            {
                id: 'ichthyostega',
                name: '鱼石螈',
                period: '3.65-3.60亿年前',
                startYear: 365,
                endYear: 360,
                type: 'land',
                lat: 20,
                lon: -60,
                icon: '🦎',
                color: 0x4caf50,
                size: '1-1.5米',
                diet: '肉食/杂食',
                habitat: '水陆交界',
                status: '灭绝',
                description: '最早的四足动物之一，具有明显的四肢和指头。虽然能在陆地上移动，但可能主要在水中生活。它是两栖动物的祖先。'
            },
            
            // ===== 石炭纪 (3.59-2.99亿年前) =====
            {
                id: 'meganeura',
                name: '巨脉蜻蜓',
                period: '3.05-2.99亿年前',
                startYear: 305,
                endYear: 299,
                type: 'flying',
                lat: 10,
                lon: 20,
                icon: '🦋',
                color: 0x9c27b0,
                size: '翼展75厘米',
                diet: '肉食',
                habitat: '森林',
                status: '灭绝',
                description: '史上最大的飞行昆虫，翼展可达75厘米。巨大的体型得益于石炭纪高氧环境。它捕食其他昆虫和小型脊椎动物。'
            },
            {
                id: 'arthropleura',
                name: '节胸蜈蚣',
                period: '3.45-2.80亿年前',
                startYear: 345,
                endYear: 280,
                type: 'land',
                lat: 25,
                lon: -10,
                icon: '🐛',
                color: 0x795548,
                size: '可达2.6米',
                diet: '植食',
                habitat: '森林',
                status: '灭绝',
                description: '史上最大的陆生无脊椎动物，一种巨型马陆。虽然体型骇人，但它是植食性的。高氧环境让它能够长到惊人的尺寸。'
            },
            {
                id: 'hylonomus',
                name: '林蜥',
                period: '3.12亿年前',
                startYear: 312,
                endYear: 311,
                type: 'land',
                lat: 35,
                lon: -50,
                icon: '🦎',
                color: 0x4caf50,
                size: '20-30厘米',
                diet: '昆虫',
                habitat: '森林',
                status: '灭绝',
                description: '最早的爬行动物之一，产羊膜卵，完全摆脱了对水体的依赖。这标志着脊椎动物真正征服了陆地。'
            },
            
            // ===== 二叠纪 (2.99-2.52亿年前) =====
            {
                id: 'dimetrodon',
                name: '异齿龙',
                period: '2.95-2.70亿年前',
                startYear: 295,
                endYear: 270,
                type: 'land',
                lat: 30,
                lon: -100,
                icon: '🦎',
                color: 0xff5722,
                size: '1-4米',
                diet: '肉食',
                habitat: '干旱平原',
                status: '灭绝',
                description: '著名的"背帆"爬行动物，常被误认为恐龙。它是盘龙类，比恐龙出现得更早。背帆可能用于体温调节。它是当时最大的掠食者之一。'
            },
            {
                id: 'scutosaurus',
                name: '盾甲龙',
                period: '2.60-2.52亿年前',
                startYear: 260,
                endYear: 252,
                type: 'land',
                lat: 45,
                lon: 60,
                icon: '🐢',
                color: 0x8bc34a,
                size: '可达3米',
                diet: '植食',
                habitat: '干旱地区',
                status: '灭绝',
                description: '一种大型的副爬行动物，身体覆盖着厚重的骨板。它是二叠纪的大型植食动物，能够防御大多数掠食者。'
            },
            
            // ===== 三叠纪 (2.52-2.01亿年前) =====
            {
                id: 'coelophysis',
                name: '腔骨龙',
                period: '2.15-1.96亿年前',
                startYear: 215,
                endYear: 196,
                type: 'land',
                lat: 25,
                lon: -105,
                icon: '🦖',
                color: 0x4caf50,
                size: '3-4米',
                diet: '肉食',
                habitat: '沙漠/河流',
                status: '灭绝',
                description: '最早的恐龙之一，轻盈的双足肉食恐龙。它体型小巧但行动敏捷，代表了三叠纪恐龙演化的早期阶段。'
            },
            {
                id: 'plateosaurus',
                name: '板龙',
                period: '2.14-2.04亿年前',
                startYear: 214,
                endYear: 204,
                type: 'land',
                lat: 40,
                lon: 10,
                icon: '🦕',
                color: 0x8bc34a,
                size: '可达10米',
                diet: '植食',
                habitat: '森林',
                status: '灭绝',
                description: '最早的大型恐龙之一，也是第一种被科学命名的恐龙。它是植食性的蜥脚类恐龙，能够双足站立取食高处的植物。'
            },
            {
                id: 'icthyosaur',
                name: '鱼龙',
                period: '2.50-9.0百万年前',
                startYear: 250,
                endYear: 90,
                type: 'marine',
                lat: 20,
                lon: 135,
                icon: '🐬',
                color: 0x2196f3,
                size: '1-15米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '鱼龙是爬行动物重返海洋的典范，外形酷似海豚。它们完全适应了海洋生活，是高效的游泳者和捕食者。'
            },
            
            // ===== 侏罗纪 (2.01-1.45亿年前) =====
            {
                id: 'allosaurus',
                name: '异特龙',
                period: '1.55-1.45亿年前',
                startYear: 155,
                endYear: 145,
                type: 'land',
                lat: 35,
                lon: -110,
                icon: '🦖',
                color: 0xf44336,
                size: '8-12米',
                diet: '肉食',
                habitat: '平原/森林',
                status: '灭绝',
                description: '侏罗纪北美洲的顶级掠食者，比霸王龙早出现近1亿年。它拥有巨大的头骨和锋利的牙齿，能捕食大型蜥脚类恐龙。'
            },
            {
                id: 'brachiosaurus',
                name: '腕龙',
                period: '1.54-1.53亿年前',
                startYear: 154,
                endYear: 153,
                type: 'land',
                lat: 40,
                lon: -105,
                icon: '🦕',
                color: 0x8bc34a,
                size: '18-26米',
                diet: '植食',
                habitat: '森林',
                status: '灭绝',
                description: '侏罗纪最高大的恐龙之一，前肢比后肢长，能够取食高处的树冠。它的心脏需要极大的压力才能将血液输送到头部。'
            },
            {
                id: 'stegosaurus',
                name: '剑龙',
                period: '1.55-1.50亿年前',
                startYear: 155,
                endYear: 150,
                type: 'land',
                lat: 38,
                lon: -108,
                icon: '🦕',
                color: 0x4caf50,
                size: '9米',
                diet: '植食',
                habitat: '平原',
                status: '灭绝',
                description: '最著名的植食恐龙之一，背上有两排骨板和四根尖刺。它的脑很小，但骨盆有一个"第二大脑"的神经节。'
            },
            {
                id: 'archaeopteryx',
                name: '始祖鸟',
                period: '1.50-1.48亿年前',
                startYear: 150,
                endYear: 148,
                type: 'flying',
                lat: 45,
                lon: 11,
                icon: '🦅',
                color: 0xff9800,
                size: '约0.5米',
                diet: '昆虫/小型动物',
                habitat: '森林',
                status: '灭绝',
                description: '最著名的过渡化石，兼具恐龙和鸟类的特征。它有羽毛和翅膀，但也保留牙齿和尾骨。是恐龙演化为鸟类的关键证据。'
            },
            
            // ===== 白垩纪 (1.45-6600万年前) =====
            {
                id: 'trex',
                name: '霸王龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'land',
                lat: 45,
                lon: -105,
                icon: '🦖',
                color: 0x795548,
                size: '12-13米',
                diet: '肉食',
                habitat: '平原/森林',
                status: '灭绝',
                description: '最著名的恐龙，也是最大的陆地掠食者之一。它拥有所有陆地动物中最强的咬合力，咬合力可达数万牛顿。小短手是其标志性特征。'
            },
            {
                id: 'triceratops',
                name: '三角龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'land',
                lat: 48,
                lon: -102,
                icon: '🦕',
                color: 0x8bc34a,
                size: '8-9米',
                diet: '植食',
                habitat: '平原',
                status: '灭绝',
                description: '最著名的植食恐龙之一，有三只角和巨大的颈盾。它可能用角进行防御和种内竞争。是霸王龙的同时代邻居。'
            },
            {
                id: 'velociraptor',
                name: '伶盗龙',
                period: '7500-7100万年前',
                startYear: 75,
                endYear: 71,
                type: 'land',
                lat: 40,
                lon: 70,
                icon: '🦖',
                color: 0xff5722,
                size: '约2米',
                diet: '肉食',
                habitat: '沙漠',
                status: '灭绝',
                description: '聪明的掠食恐龙，身披羽毛，第二趾有镰刀状利爪。虽然体型比电影中小得多，但群体狩猎时非常危险。'
            },
            {
                id: 'pteranodon',
                name: '无齿翼龙',
                period: '8800-8050万年前',
                startYear: 88,
                endYear: 80.5,
                type: 'flying',
                lat: 35,
                lon: -95,
                icon: '🦅',
                color: 0x00bcd4,
                size: '翼展7米',
                diet: '鱼类',
                habitat: '海岸',
                status: '灭绝',
                description: '不是恐龙，而是会飞的爬行动物。巨大的头冠可能有多种功能，包括展示、体温调节和飞行稳定。'
            },
            {
                id: 'mosasaurus',
                name: '沧龙',
                period: '8200-6600万年前',
                startYear: 82,
                endYear: 66,
                type: 'marine',
                lat: 30,
                lon: -90,
                icon: '🐊',
                color: 0x3f51b5,
                size: '可达17米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '白垩纪海洋的顶级掠食者，巨大的海生蜥蜴。它拥有强壮的尾巴和四肢演化成的鳍，统治着白垩纪晚期的海洋。'
            },
            {
                id: 'tyrannosaurus',
                name: '霸王龙',
                period: '6800-6600万年前',
                startYear: 68,
                endYear: 66,
                type: 'land',
                lat: 45,
                lon: -100,
                icon: '🦖',
                color: 0x795548,
                size: '12-13米',
                diet: '肉食',
                habitat: '平原',
                status: '灭绝',
                description: '白垩纪晚期最大的掠食者，拥有所有陆地动物中最强的咬合力。它那看似滑稽的小短手，其实可能用于抓握猎物。'
            },
            
            // ===== 古近纪 (6600-2300万年前) =====
            {
                id: 'gastornis',
                name: '加斯顿鸟',
                period: '5600-4500万年前',
                startYear: 56,
                endYear: 45,
                type: 'land',
                lat: 50,
                lon: 2,
                icon: '🐦',
                color: 0xff9800,
                size: '高约2米',
                diet: '肉食/植食',
                habitat: '森林',
                status: '灭绝',
                description: '巨大的不会飞的鸟类，有巨大的喙。它曾是古新世的顶级掠食者之一，填补了恐龙灭绝后的生态位。'
            },
            {
                id: 'uintatherium',
                name: '尤因它兽',
                period: '5600-3400万年前',
                startYear: 56,
                endYear: 34,
                type: 'land',
                lat: 40,
                lon: -110,
                icon: '🦏',
                color: 0x8d6e63,
                size: '可达4米',
                diet: '植食',
                habitat: '森林/沼泽',
                status: '灭绝',
                description: '早期的巨型植食哺乳动物，头部有多个骨质突起和尖牙。它代表了哺乳动物体型增大的早期尝试。'
            },
            {
                id: 'basilosaurus',
                name: '龙王鲸',
                period: '4100-3400万年前',
                startYear: 41,
                endYear: 34,
                type: 'marine',
                lat: 25,
                lon: 30,
                icon: '🐋',
                color: 0x607d8b,
                size: '可达18米',
                diet: '肉食',
                habitat: '浅海',
                status: '灭绝',
                description: '早期的鲸鱼，具有细长的身体和微小的后肢。它是鲸类从陆地返回海洋演化过程中的过渡类型。'
            },
            {
                id: 'paraceratherium',
                name: '巨犀',
                period: '3400-2300万年前',
                startYear: 34,
                endYear: 23,
                type: 'land',
                lat: 35,
                lon: 65,
                icon: '🦏',
                color: 0x795548,
                size: '肩高4.8米',
                diet: '植食',
                habitat: '草原/森林',
                status: '灭绝',
                description: '史上最大的陆地哺乳动物，体型可与蜥脚类恐龙相比。它没有角，依靠巨大的体型来防御掠食者。'
            },
            
            // ===== 新近纪 (2300万年-260万年前) =====
            {
                id: 'megalodon',
                name: '巨齿鲨',
                period: '2300-360万年前',
                startYear: 23,
                endYear: 3.6,
                type: 'marine',
                lat: 20,
                lon: -75,
                icon: '🦈',
                color: 0x607d8b,
                size: '可达18米',
                diet: '肉食',
                habitat: '海洋',
                status: '灭绝',
                description: '史上最大的掠食性鱼类，牙齿可达18厘米。它能捕食鲸鱼和其他大型海洋动物，是有史以来最强大的掠食者之一。'
            },
            {
                id: 'smilodon',
                name: '剑齿虎',
                period: '250万年前-1万年前',
                startYear: 2.5,
                endYear: 0.01,
                type: 'land',
                lat: -25,
                lon: -60,
                icon: '🐅',
                color: 0xff9800,
                size: '可达400公斤',
                diet: '肉食',
                habitat: '草原/森林',
                status: '灭绝',
                description: '著名的剑齿猫科动物，拥有超长的上犬齿。它用强壮的前肢制服猎物，然后用利齿给予致命一击。'
            },
            {
                id: 'woolly_mammoth',
                name: '猛犸象',
                period: '40万年前-4000年前',
                startYear: 0.4,
                endYear: 0.004,
                type: 'land',
                lat: 65,
                lon: 75,
                icon: '🐘',
                color: 0x9e9e9e,
                size: '肩高3.4米',
                diet: '植食',
                habitat: '苔原/草原',
                status: '灭绝',
                description: '冰河时代的标志性动物，身披厚毛，长有弯曲的长牙。它们适应了寒冷的北极环境，与人类共存了很长时间。'
            },
            {
                id: 'australopithecus',
                name: '南方古猿',
                period: '400-200万年前',
                startYear: 4,
                endYear: 2,
                type: 'land',
                lat: -25,
                lon: 25,
                icon: '🦍',
                color: 0x8d6e63,
                size: '身高1-1.4米',
                diet: '杂食',
                habitat: '稀树草原',
                status: '灭绝（有人类后代）',
                description: '最早的人科动物之一，著名的"露西"就属于这个属。它们已经能够直立行走，但脑容量还很小。是人类演化路上的重要一步。'
            },
            
            // ===== 第四纪 (260万年前-现在) =====
            {
                id: 'neanderthal',
                name: '尼安德特人',
                period: '40-4万年前',
                startYear: 0.4,
                endYear: 0.04,
                type: 'land',
                lat: 50,
                lon: 10,
                icon: '🧑',
                color: 0xd7ccc8,
                size: '身高1.6-1.7米',
                diet: '肉食为主',
                habitat: '欧洲/西亚',
                status: '灭绝（部分基因融入人类）',
                description: '现代人的近亲，适应寒冷气候。他们有埋葬死者的习俗，可能使用语言和符号。现代人类有1-4%的尼安德特人基因。'
            },
            {
                id: 'saber_toothed_cat',
                name: '刃齿虎',
                period: '250万年前-1万年前',
                startYear: 2.5,
                endYear: 0.01,
                type: 'land',
                lat: 35,
                lon: -120,
                icon: '🐅',
                color: 0xff5722,
                size: '可达880公斤',
                diet: '肉食',
                habitat: '多种环境',
                status: '灭绝',
                description: '著名的剑齿猫科动物，拥有超长的上犬齿。它用强壮的前肢制服猎物，然后用利齿给予致命一击。'
            },
            {
                id: 'ground_sloth',
                name: '大地懒',
                period: '350万年前-1万年前',
                startYear: 3.5,
                endYear: 0.01,
                type: 'land',
                lat: -15,
                lon: -60,
                icon: '🦥',
                color: 0x8d6e63,
                size: '可达6米',
                diet: '植食',
                habitat: '森林/草原',
                status: '灭绝',
                description: '巨大的地懒，体型可与大象相比。它能够用后足站立取食高处的树叶，是最大的陆生树懒。'
            }
        ];
    }
    
    // 获取指定年代存在的生物
    getCreaturesAtYear(year) {
        return this.creatures.filter(creature => {
            return year <= creature.startYear && year >= creature.endYear;
        });
    }
    
    // 根据ID获取生物
    getCreatureById(id) {
        return this.creatures.find(c => c.id === id);
    }
    
    // 按类型筛选生物
    getCreaturesByType(type) {
        return this.creatures.filter(c => c.type === type);
    }
    
    // 搜索生物
    searchCreatures(query) {
        const lowerQuery = query.toLowerCase();
        return this.creatures.filter(c => 
            c.name.toLowerCase().includes(lowerQuery) ||
            c.description.toLowerCase().includes(lowerQuery)
        );
    }
    
    // 获取所有生物
    getAllCreatures() {
        return this.creatures;
    }
    
    // 获取生物类型统计
    getTypeStats() {
        const stats = {};
        this.creatures.forEach(c => {
            stats[c.type] = (stats[c.type] || 0) + 1;
        });
        return stats;
    }
}
